sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
<<<<<<< HEAD
    access-key-id:
    access-key-secret:
=======
    access-key-id:
    access-key-secret:
>>>>>>> 0af0a27 (更改了一些信息)
    bucket-name: iefaaa
<<<<<<< HEAD
=======
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
<<<<<<< HEAD
=======
  wechat:
<<<<<<< HEAD
    appid:
    secret:
>>>>>>> fe24a12 (套餐业务和微信登录业务模块)
<<<<<<< HEAD
>>>>>>> b6e7b9e (店铺营业状态设置业务)
=======
=======
    appid:
    secret:
>>>>>>> 0af0a27 (更改了一些信息)
>>>>>>> 8e1b252 (更新了readme)
